### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by corentincarton** [ecmwf/pyflow-wellies#4]
### Is your feature request related to a problem? Please describe.

Some things that should be changed for next release:

- [x] ~Get rid of definition file and talk directly to the ecflow server (via pyflow? or tracksuite?)~ New tracksuite tools should deal with this use case.
- [ ] #43
- [x] Rename parse_static_data_item into parse_data_item
- [x] #38
- [x] ~Find a way to specify module version through ecflow variables (maybe an optional "variable" option could be added to all the tools)~ The new `ecflow_variables` special key should help with this use case. Where you can define in tools.yaml variables to control the modules version that will be added at the suite level.
- [x] #39
- [x] Update install procedure in readme and docs to use pyflow-wellies from PyPI directly
- [x] #40
- [X] point to readthedocs for the documentation https://pyflow-wellies.readthedocs.io
- [x] ~add copy_options for the data type "copy"~ (as we have for rsync) #44 
- [x] ~add description execution context through Troika in the documentation~ should this be in pyflow documentation?
- [x] ~add mars_command to static_data yaml config~ #44 
- [x] add data_dir attribute for StaticData class to retrieve the path where the data is stored
- [ ] #41
- [x] #42
- [x] From #27 , add a `build_dir` optional where relevante, i.e, `PackageTool` and `GitData` types.

**Comment by colonesej** [comment]
Add `version` as ecflow variable at suite level for any module provided.  Use wellies tools key, which is already unique, as variable name.

**Comment by corentincarton** [comment]
This is something we discussed with @oiffrig a few weeks ago as it was needed in one of the operational suites. There's a way to do this without modifying the wellies code:
```
tools:
  modules:
    python:
      name: python3
      version: ${PYTHON_VERSION:-3.10}
   python_new:
      name: python3
      version: ${PYTHON_VERSION_NEW:-3.12}
```
The good thing with this approach is that it doesn't pollute your list of variables by default and you can just add the variable to the suite when you need it. But I agree it's not straightforward, so maybe it could be featured in the documentation or the quickstart?

**Comment by colonesej** [comment]
How about changing pyflow to identify bash variables in scripts with defaults and treat them as exportables even if not defined on a node/tree?

**Comment by corentincarton** [comment]
Ah yes, you're right, it will need to be identified in the script generation otherwise the variable will not be exported. Not sure it's safe to do that automatically in pyflow... I would prefer your first suggestion. What bothers me is that we do all sorts of gymnastics when we could use directly ecflow variables with default values %PYTHON_VERSION:3.12% :D

**Comment by colonesej** [comment]
Another thing that came to me (it might not belong to wellies but maybe tracksuits, not sure):
- Deploy one yaml file with the final parsed configuration used to generate the suite to `deploy_dir`
- add, as a comment, on top of the config a message including timestamp and git-based info of source project, example
`# deployed with tracksuite from efas@release/5.1+12314312321asdve324234`

Second one could be replaced by tracksuite commit message but do we include there information about the git state of the source project by default?

**Comment by corentincarton** [comment]
Yes we could definitely do that! It doesn't belong in tracksuite, but more in wellies. We already have add a wellies-specific message which includes the version of wellies used to deploy the suite, but we could add the local git hash/branch/tag as well if we find one.

**Comment by colonesej** [comment]
Closing after #23 and pending issues have their own entry as linked in listing.
